### ISSUE TITLE
RF18	O visitante deve poder editar e recuperar a senha cadastrada no sistema.

### ISSUE THREAD

**Issue by viniciustrindade** [ic0045/eventscomp#11]

**Comment by viniciustrindade** [comment]
@IsaqueCopque falta intergrar com o sendgrid
@cristh1an falta a tela de mudar senha.

**Comment by IsaqueCopque** [comment]
Funcionalidade de envio de e-mail de confirmação implementada.

**Comment by IsaqueCopque** [comment]
Funcionalidade de recuperação de senha implementada.
Falta tela para inserir nova senha.

**Comment by IsaqueCopque** [comment]
Tela feita por Christian.
Funcionalidade corrigida.
